authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('create/', views.register_create, name='create'),
    path('login/', views.login_view, name='login'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views


app_name = 'recipes'

urlpatterns = [
    path('recipes/search/', views.search, name="search"),
    path('', views.home, name="home"),
    path('recipes/category/<int:category_id>/', views.category, name="category"),  # noqa: E501
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.PositiveIntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.PositiveIntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y-%m-%d/', blank=True, default=''
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, default=None)  # noqa: E501
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)  # noqa: E501

    def __str__(self):
        return self.title

recipes/models/recipe.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=65)
    def __str__(self):
        return self.name

class Recipe(models.Model):
    id = models.CharField(max_length=6, primary_key=True)
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.PositiveIntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.PositiveIntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y-%m-%d/')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.title

recipes/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from .models import Recipe
from django.core.paginator import Paginator
from utils.pagination import make_pagination_range

import os

PER_PAGE = int(os.environ.get('PER_PAGE', 9))


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by("-id")
    try:
        current_page = int(request.GET.get('page', 1))
    except ValueError:
        current_page = 1
    paginator = Paginator(recipes, PER_PAGE)
    page_obj = paginator.get_page(current_page)

    pagination_range = make_pagination_range(
        paginator.page_range,
        4,
        int(current_page)
    )

    return render(request, 'recipes/pages/home.html', context={
        "recipes": page_obj,
        "pagination_range": pagination_range,
        "current_page": current_page,
        "page_title": "Home | Recipes"})


def category(request, category_id):
    recipes = Recipe.objects.filter(category__id=category_id, is_published=True).order_by("-id")  # noqa: E501

    try:
        current_page = int(request.GET.get('page', 1))
    except ValueError:
        current_page = 1
    paginator = Paginator(recipes, PER_PAGE)
    page_obj = paginator.get_page(current_page)

    pagination_range = make_pagination_range(
        paginator.page_range,
        4,
        int(current_page)
    )
    if not recipes:
        return render(request, 'recipes/pages/404.html', status=404)

    return render(request, 'recipes/pages/category.html', context={
        "recipes": page_obj,
        "pagination_range": pagination_range,
        "current_page": current_page,
        "title": f"{recipes[0].category.name}-Category | "})


def recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id, is_published=True)
    return render(request, 'recipes/pages/recipe-view.html', context={
        "recipe": recipe,
        "title": f"{recipe.title}",
        "is_detail_page": True})


def search(request):
    search_item = request.GET.get('q', '').strip()
    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_item) |
            Q(description__icontains=search_item)
        ),
        is_published=True,
        ).order_by("-id")  # noqa: E501

    try:
        current_page = int(request.GET.get('page', 1))
    except ValueError:
        current_page = 1
    paginator = Paginator(recipes, PER_PAGE)
    page_obj = paginator.get_page(current_page)

    pagination_range = make_pagination_range(
        paginator.page_range,
        4,
        int(current_page)
    )

    if not search_item:
        return render(request, 'recipes/pages/404.html', status=404)
    else:
        return render(request, 'recipes/pages/search.html', {
            'page_title': f'Search for "{search_item}"',
            'search_term': search_item,
            "recipes": page_obj,
            "pagination_range": pagination_range,
            "current_page": current_page,
        })

recipes/templates/recipes/partials/head.html
{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
    integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{% static "recipes/css/styles.css" %}">
<link rel="stylesheet" href="{% static "global/css/global-style.css" %}">

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url "recipes:recipe" recipe.id%}">
            <img src="{{recipe.cover.url}}" alt="Temporário">
        </a>
    </div>
    <div class="recipe-title-container">
        <a href="{% url "recipes:recipe" recipe.id%}">
            <h2 class="recipe-title">{{recipe.title}}</h2>
        </a>
    </div>

    <div class="recipe-author">
        {% if recipe.author is not None %}
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author.first_name %}
                    {{recipe.author.first_name}} {{recipe.author.first_name}}
                    {% else %}
                        {{recipe.author.username}}
                </span>
            {% endif %}
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:"d/m/Y"}} às {{recipe.created_at|date:"H:i"}}
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True%}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url "recipes:recipe" recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}
    {% if is_detail_page is True%}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{recipe.preparation_steps|safe}}
            {% else %}
                {{recipe.preparation_steps|linebreaksbr}}
            {% endif %}
        </div>
    {% endif %}

</div>